spring:
  # datasource:
    # url: jdbc:postgresql://host.docker.internal:5432/db
    # username: postgres
    # password: password
  # h2:
  #   console:
  #     enabled: true
  jpa:
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
# s3:
#   buckets:
#     illustrations: examillustrations
#     photos: examphotos
#   hostname: http://127.0.0.1:9000
#   access_key: VrxI8xqvw4veHiJmvlx1
#   secret_key: znFFrTYNoEAdCQDShvDjE47hPJikdz2zzAyyWpNk